export const products = [
    {
        id:1,
        img:'/14ct Yellow Gold Signe.png',
        name:'14ct Yellow Gold Signe',
        price: "$199",
        rating: "4.5/5",
    },
    {
        id:2,
        img:'/Amethyst Crystal.png',
        name:'Amethyst Crystal',
        price: "$240",
      discountPrice: "$145",
      discount: "-20%",
      rating: "4.5/5",
    },
    {
        id:3,
        img:'/Amethyst Cactus.png',
        name:'Amethyst Cactus.png',
        price: "$80",
      rating: "4.5/5",

    },
    {
        id:4,
        img:'/Emerald Stone.png',
        name:'Emerald Stone',
        price: "$130",
        originalPrice: "$210",
        discount: "-30%",
        rating: "4.5/5",
    },
    {
        id:5,
        img:'/Emmamarty Chinesewriting stone.png',
        name:'Emmamarty Chinesewriting stone',
        price: "$130",
      originalPrice: "$160",
      discount: "-30%",
      rating: "4.5/5",
    },
    {
        id:6,
        img:'/Gems Of Sri Lanka, Stone, Purple.png',
        name:'Gems Of Sri Lanka, Stone, Purple',
        price: "$130",
      originalPrice: "$160",
      discount: "-30%",
      rating: "4.5/5",
    },
    {
        id:7,
        img:'/Gems Of War Doom.png',
        name:'Gems Of War Doom',
        price: "$170",
      originalPrice: "$160",
      discount: "-30%",
      rating: "4.5/5",
    },
    {
        id:8,
        img:'/Gentiana Stone.png',
        name:'Gentiana Stone',
        price: "$130",
      originalPrice: "$160",
      discount: "-30%",
      rating: "4.5/5",
    },
    {
        id:9,
        img:'/Green Obsidian Stone.webp',
        name:'Green Obsidian Stone',
        price: "$230",
        rating: "4.5/5",
    },
    {
        id:10,
        img:'/Purple Amethyst.png',
        name:'Green Obsidian Stone',
        price: "$80",
        rating: "4.5/5",
    },
    {
        id:11,
        img:'/Gentiana Stone.png',
        name:'Gentiana Stone',
        price: "$99",
        rating: "4.5/5",
    },
    {
        id:12,
        img:'/Madeleine Green Cocktail.png',
        name:'Madeleine Green Cocktail',
        price: "$212",
        rating: "4.5/5",
    },
    {
        id:13,
        img:'/Mens Lapis Lazuli Signe.png',
        name:'Mens Lapis Lazuli Signe',
        price: "$200",
        rating: "4.5/5",
    },
    {
        id:14,
        img:'/Obsidian gemstone.png',
        name:'Obsidian gemstone',
        price: "$212",
        rating: "4.5/5",
    },
    {
        id:15,
        img:'/Orange And Purple Crystal.png',
        name:'Orange And Purple Crystal',
        price: "$212",
        rating: "4.5/5",
    },
    {
        id:16,
        img:'/Platinum Bloodstone Signet.png',
        name:'Platinum Bloodstone Signet',
        price: "$70",
        rating: "4.5/5",
    },
    {
        id:17,
        img:'/PngItem_1497852.png',
        name:'Madeleine Obsidian',
        price: "$79",
        rating: "4.5/5",
    },
    {
        id:18,
        img:'/PngItem_2856279.png',
        name:'Gentiana obsidioun stone',
        price: "$60",
        rating: "4.5/5",
    },
    {
        id:19,
        img:'/PngItem_3809049.png',
        name:'Peridot Stone',
        price: "$212",
        rating: "4.5/5",
    },
    {
        id:20,
        img:'/PngItem_4263731.png',
        name:'Zircon stone',
        price: "$212",
        rating: "4.5/5",
    },
    {
        id:21,
        img:'/PngItem_4263731.png',
        name:"Tiger’s Eye Stone",
        price: "$130",
      originalPrice: "$160",
      discount: "-30%",
      rating: "4.5/5",
    },
    {
        id:22,
        img:'/PngItem_5285542.png',
        name:'Onyx stone',
        price: "$130",
      originalPrice: "$160",
      discount: "-30%",
      rating: "4.5/5",
    },
    {
        id:23,
        img:'/PngItem_6181178.png',
        name:'Jade stone',
        price: "$130",
      originalPrice: "$160",
      discount: "-30%",
      rating: "4.5/5",
    },
    {
        id:24,
        img:'/Purple Amethyst.png',
        name:'Purple Amethyst',
        price: "$130",
      originalPrice: "$199",
      discount: "-30%",
      rating: "4.5/5",
    },
    {
        id:25,
        img:'/Stone Set Oval Signet.png',
        name:'Stone Set Oval Signet',
        price: "$130",
        originalPrice: "$149",
        discount: "-30%",
        rating: "4.5/5",
    
    },
    {
        id:26,
        img:'/Ruby Diamond.png',
        name:'Ruby Diamond',
        price: "$130",
        originalPrice: "$70",
        discount: "-30%",
        rating: "4.5/5",
    },
    {
        id:27,
        img:'/Swarovski 4120 Oval Fancy Stone Crystal Laguna Delite.png',
        name:'Swarovski 4120 Oval Fancy Stone Crystal Laguna Delite',
        price: "$130",
        originalPrice: "$210",
        discount: "-30%",
        rating: "4.5/5",
    },
    {
        id:28,
        img:'/Swarovski 4142 Baroque Mirror Fancy Stone.png',
        name:'Swarovski 4142 Baroque Mirror Fancy Stone',
        price: "$130",
        originalPrice: "$280",
        discount: "-30%",
        rating: "4.5/5",
    },
    {
        id:29,
        img:'/Swarovski 4470 Cushion Square Fancy Stone Crystal Laguna.png',
        name:'Swarovski Cushion Square Fancy Stone Crystal ',
        price: "$130",
        originalPrice: "$210",
        discount: "-30%",
        rating: "4.5/5",
    },
    {
        id:30,
        img:'/Swarovski 5000 Light Amethyst.png',
        name:'Swarovski Light Amethyst',
        price: "$130",
        originalPrice: "$89",
        discount: "-30%",
        rating: "4.5/5",
    },
    {
        id:31,
        img:'/Swarovski Pear Stone.png',
        name:'Swarovski Pear Stone',
        price: "$199",
        rating: "4.5/5",
    },
    {
        id:32,
        img:'/Transparent Ice Crown.png',
        name:'Transparent Ice Crown',
        price: "$139",
        rating: "4.5/5",
    },
    {
        id:33,
        img:'/Tumbled Amethyst.png',
        name:'Tumbled Amethyst',
        price: "$199",
        rating: "4.5/5",
    }
]
